
spring.application.name=sce-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/sce_platform
spring.datasource.username=postgres
spring.datasource.password=postgres

management.endpoints.web.exposure.include=health,info

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true